//"Historia powszechna i teorie stosunków międzynarodowych"
//Blok1
const baza1 = `ID;Pytanie;A;B;C;D;Klucz
1;W okresie przednowożytnym stosunki międzynarodowe miały:;chaotyczny i nieuporządkowany charakter;zasięg globalny;ograniczały się do podboju lub kontaktów handlowych;odpowiedź A i C;D
2;Pierwszy w dziejach system państw powstał:;w Ameryce Łacińskiej w XIX wieku;w Europie po wojnie 30-letniej (w XVII wieku);w Afryce i Azji po dekolonizacji w połowie XX wieku;po II wojnie światowej w ramach systemu Narodów Zjednoczonych;B
3;Nowopowstałe państwa w Ameryce Łacińskiej stały się członkami systemu państw:;w XVI wieku wskutek kolonizacji;po dekolonizacji w połowie XX wieku;po uzyskaniu niepodległości w XIX wieku;po przyjęciu do ONZ;C
4;Human Rights Watch to przykład organizacji międzynarodowej:;pozarządowej;międzyrządowej;odpowiedź A i D;zajmującej się ochroną praw człowieka;C
5;Organizacja Narodów Zjednoczonych jest:;organizacją międzynarodową pozarządową;organizacją międzynarodową międzyrządową;organizacją o zasięgu globalnym;odpowiedź B i C;D
6;Ograniczenia suwerenności państw mogą następować wskutek:;dobrowolnego przekazania części suwerennych praw na rzecz struktur ponadnarodowych;ingerencji podmiotów zewnętrznych;słabości wewnętrznej państwa;wszystkie z powyższych;D
7;Sudan Południowy to przykład państwa, które powstało wskutek:;połączenia (dobrowolnej unii);secesji (oderwania części terytorium);dekolonizacji;rezolucji Zgromadzenia Ogólnego ONZ;B
8;Którą z poniższych grupę państw możemy zaliczyć obecnie do grona państw upadłych/upadających?;Albania, Kosowo, Korea Północna;Haiti, Somalia, Jemen;Kolumbia, Brazylia, Argentyna;Mołdawia, Kazachstan, Gruzja;B
9;Pięcioma stałymi członkami Rady Bezpieczeństwa ONZ z prawem weta są:;ChRL, Niemcy, Rosja, USA, Wielka Brytania;USA, ChRL, Rosja, Niemcy, Japonia;USA, ChRL, Indie, Francja, Wielka Brytania;ChRL, Francja, Rosja, USA, Wielka Brytania;D
10;Do składników soft power (miękkiej siły) państwa zaliczamy:;potencjał gospodarczy i demograficzny państwa;potencjał kulturowy i jakość dyplomacji państwa;odpowiedź B i D;jakość edukacji i poziom rozwoju społecznego państwa;C
11;Przekonanie, że nie istnieje żadna określona z góry natura państw a interesy i tożsamości państw są zmienne, to składnik myśli:;realistycznej;konstruktywizmu;liberalnej;neomarksistowskiej;B
12;Rozumienie świata, w tym stosunków międzynarodowych, zależy od tekstów na jego temat - takie stwierdzenie mogło paść ze strony zwolenników:;racjonalistycznych teorii stosunków międzynarodowych;postmodernistycznych teorii stosunków międzynarodowych;liberalnej teorii stosunków międzynarodowych;teorii społeczności międzynarodowej;B
13;Geopolityczna koncepcja potęgi kontynentalnej Halforda Mackindera zakładała:;podział świata na strefy wpływów wielkich mocarstw;kluczowe znaczenie panowania na oceanie światowym;rywalizację między potęgami morskimi i lądowymi o dominację w Eurazji;kluczowe znaczenie Półkuli Zachodniej dla losów świata;C
14;Neoliberalna ocena globalizacji w ramach teorii stosunków międzynarodowych:;uznaje poważne konsekwencje globalizacji dla stosunków międzynarodowych;zakłada niewielkie znaczenie globalizacji dla zmiany charakteru stosunków międzynarodowych;odpowiedź A i D;zakłada, że zjawisko globalizacji ma wpływ na osłabienie suwerenności państw;C
15;Tzw. realizm defensywny to nurt w obrębie szkoły neorealistycznej zakładający, iż:;państwa dążą przede wszystkim do utrzymania równowagi sił;państwa zawsze dążą do maksymalizacji swojej potęgi;państwa kierują się raczej obawą niż wizją ewentualnych korzyści;odpowiedź A i C;D
16;Wskaż poprawny zestaw autorów i ich teorii stosunków międzynarodowych:;Hans Morgenthau (konstruktywizm), Halford Mackinder (geopolityka), Alexander Wendt (realizm);Hans Morgenthau (konstruktywizm), Halford Mackinder (realizm), Alexander Wendt (geopolityka);Hans Morgenthau (realizm), Halford Mackinder (geopolityka), Alexander Wendt (konstruktywizm);Hans Morgenthau (geopolityka), Halford Mackinder (konstruktywizm), Alexander Wendt (realizm);C
17;Które z poniższych doktryn politycznych są uznane za doktryny reformistyczne:;komunizm i socjalizm;konserwatyzm i liberalizm;anarchizm;chrześcijańska demokracja i socjaldemokracja;D
18;W których państwach współcześnie rządy sprawuje wyłącznie jedna partia polityczna, odwołująca się do ideologii komunizmu?;w Albanii i Republice Chińskiej na Tajwanie;w Rumunii i Kambodży;w Chińskiej Republice Ludowej i Wietnamie;w Arabii Saudyjskiej i Wenezueli;C
19;Idea Objawionego Przeznaczenia (Manifest Destiny) z 1845 roku to ideowa podstawa ekspansji terytorialnej i imperialnych dążeń:;Francji w Afryce Zachodniej;kolonialnego imperium Wielkiej Brytanii;poszerzania obszaru rosyjskiego imperium w Azji Środkowej;ekspansji terytorialnej i wewnętrznej kolonizacji Stanów Zjednoczonych;D
20;Teorie hegemonicznej stabilności/światowego przywództwa:;zakładają, iż porządek międzynarodowy utrzymywany jest przez światowego hegemona;opisują zależności pomiędzy równowagą systemu a przywództwem jednego państwa;opisują proces kształtowania się i utraty hegemonii;wszystkie z powyższych;D
21;Kanclerz Niemiec Otto von Bismarck:;dążył do zawarcia sojuszu Niemiec z Francją;obawiał się rewanżu wojennego Niemiec na Francji;podtrzymywał sojusz Niemiec z Austro-Węgrami i Rosją;odpowiedzi B i C są prawdziwe;D
22;W czasie kryzysu międzynarodowego w Europie w lipcu-sierpniu 1914 roku:;Rosja poparła Serbię w obronie przed naciskiem Austro-Węgier;zginął następca tronu Niemiec arcyksiążę Franciszek Ferdynand;Włochy podtrzymały zobowiązania wobec Trójprzymierza;Francja uruchomiła plan mający na celu zdobycie Berlina;A
23;I wojna światowa została rozstrzygnięta na korzyść ententy, ponieważ:;Niemcy i Austro-Węgry narzuciły Rosji traktat pokojowy w Brześciu;na front zachodni w 1918 r. przybyły wojska USA;Francja miała więcej rezerw ludzkich niż Niemcy;Wielka Brytania i Francja ogłosiły niepodległość koloniom;B
24;Bolszewicy:;w 1918 roku zmusili cara Mikołaja II do abdykacji;w 1919 roku skolektywizowali rolnictwo;w 1920 roku podjęli militarny atak w kierunku Niemiec przez terytorium Polski;w 1921 roku stoczyli z armią polską bitwę pod Warszawą;C
25;Reżim autorytarny w Europie międzywojennej charakteryzowało/a:;propaganda na rzecz wzmocnienia państwa narodowego;odpowiedzi A i C są prawdziwe;cenzura publikacji prasowych;komunikowanie się przywódcy przez wielkie mityngi partyjne;B
26;Faszyzm w okresie międzywojennym:;wyniósł do władzy we Włoszech ludzi nieakceptujących korzyści po I wojnie;zdobył władzę w Niemczech w 1922 roku;obalił demokratyczne władze Polski w zamachu majowym;sympatyzował z republikańską stroną wojny domowej w Hiszpanii;A
27;III Rzesza:;wprowadziła zasady eugeniki do prawa państwowego;przetrwała 16 lat;okupowała Norwegię, Serbię i Portugalię;została zastąpiona przez Republikę Weimarską;A
28;ZSRR w okresie osobistych rządów Stalina (1929-1953):;włączył w swe granice Finlandię;przeprowadził deportacje Tatarów Krymskich i Czeczenów;prowadził politykę narodowościową zgodną z korenizatsyją;uwolnił od okupacji hitlerowskiej Grecję i Chorwację;B
29;Na konferencji w Teheranie (1943) Stalin, Churchill i Roosevelt:;podjęli decyzję o wspólnych działaniach przeciw Japonii;porozumieli się w sprawie otwarcia drugiego frontu we Francji;ustalili zasady denazyfikacji w strefach okupacyjnych;podjęli decyzję o wysiedleniu Niemców z terytoriów Polski;B
30;Maccartyzm był:;nurtem w ruchu komunistycznym w państwach anglosaskich;antylewicową czystką w elitach opiniotwórczych w USA;kryptonimem zespołu przygotowującego bombę atomową;symptomem rozwoju liberalnej demokracji;B
31;Armia Czerwona wkroczyła:;do Wiednia w 1945 roku oraz do Budapesztu w 1956 roku;do Helsinek w 1944 roku oraz do Pragi w 1968 roku;na południowe Kuryle w 1945 roku oraz do Pekinu w 1949 roku;do Sajgonu w 1975 roku i do Kabulu w 1979 roku;A
32;Do rozpadu partii i wojska na stronę antysowiecką i prosowiecką doszło w czasie rewolucji:;w Berlinie Wschodnim w 1953 roku;na Węgrzech w 1956 roku;w Czechosłowacji w 1968 roku;w Polsce w 1981 roku;B
33;System z Bretton Woods:;odpowiedzi B, C i D są prawdziwe;gwarantował stabilny kurs dolara w oparciu o złoto;dał podstawy funkcjonowania MFW;wiązał kursy walut z kursem dolara;A
34;W czasie zimnej wojny Stany Zjednoczone:;interweniowały zbrojnie w Korei, Wietnamie i Chile;straciły wskutek zamachu prezydenta z Partii Demokratycznej;podtrzymały reżimy w Angoli i Mozambiku;zachowały przewagę w liczbie wyrzutni atomowych;A
35;Państwami zależnymi od Związku Radzieckiego przez co najmniej dekadę były:;Albania, Etiopia i Indie;Rumunia, Kuba i Argentyna;Mongolia, Korea Północna i Wietnam;Jugosławia, Polska i Bułgaria;C
36;Państwo Izrael:;powstało w wyniku uchwały ONZ w 1947 roku;było współsprawcą kryzysu sueskiego w 1956 roku;okupowało Wzgórza Golan po wojnie 1967 roku;odpowiedzi A, B i C są prawdziwe;D
37;Rewolucja w 1968 roku miała miejsce w:;Iranie, gdzie obalono szacha;Iraku, gdzie obalono Saddama Husajna;Paryżu, gdzie wznoszono hasła maoistowskie;Etiopii, gdzie obalono cesarstwo;C
38;Jesień Narodów w 1989 roku zakończyła rządy:;Edwarda Gierka w Polsce;Josipa Broz Tito w Jugosławii;Ericha Honeckera w NRD;Kim Ir Sena w Korei Północnej;C
39;Stany Zjednoczone w okresie George'a W. Busha (2001-2009):;poprowadziły wojnę NATO przeciw Serbii;zdobyły i okupowały Irak;wsparły militarnie Gruzję wobec ataku Rosji;zabiły Osamę bin Ladena w Pakistanie;B
40;Rosja w okresie rządów Władimira Putina (od 2000 roku):;odpowiedzi B, C i D są prawdziwe;okupowała Osetię Południową;anektowała Donbas;wsparła militarnie reżim w Syrii;A`;
//"Ekonomia i międzynarodowe stosunki ekonomiczne"
//Blok2
const baza2 = `ID;Pytanie;A;B;C;D;Klucz
1;Wewnątrzgałęziowy podział pracy jest rezultatem:;Komplementarności;Substytucyjności;Konkurencyjności gospodarek;Wszystkie odpowiedzi są poprawne;C
2;Handel zagraniczny odgrywa zwykle względnie większą rolę w krajach:;dużych;małych;wyposażonych w bogate złoża surowców;prowadzących gospodarkę autarkiczną;B
3;Podstawą ładu prawnego określającego warunki funkcjonowania gospodarki danego kraju, np. Polski, jest:;konstytucja;kodeks karny;kodeks cywilny i handlowy;kodeks postępowania administracyjnego;A
4;Największy w ujęciu wartościowym udział w handlu międzynarodowym ma obecnie:;handel artykułami rolnymi;handel towarami przemysłowymi;handel usługami;handel surowcami;B
5;Rozwinięciem teorii przewagi absolutnej A. Smitha jest teoria:;kosztów komparatywnych;teoria D. Ricarda;przewagi względnej;wszystkie odpowiedzi są poprawne;D
6;Zatrudniony na Ukrainie wytwarza 3t pszenicy lub 1 samochód. W Polsce 4t pszenicy lub 2 samochody. Wynika z tego, że:;Polska ma absolutną przewagę, a Ukraina nie ma przewagi komparatywnej;Ukraina ma absolutną przewagę, a Polska nie ma przewagi komparatywnej;Polska ma absolutną przewagę, lecz Ukraina ma przewagę komparatywną w produkcji pszenicy;Polska ma absolutną przewagę, lecz Ukraina ma przewagę komparatywną w produkcji samochodów;C
7;Handel wewnątrzgałęziowy ma relatywnie największe znaczenie w krajach:;NAFTA;WNP;UE;ASEAN;C
8;Której z poniższych form napływu kapitału nie można zakwalifikować jako inwestycji bezpośrednich:;zakup przez brytyjski bank pakietu kontrolnego w polskim towarzystwie;utworzenie przez transnarodową firmę centrum obsługi na Dolnym Śląsku;wykup przez szwedzki fundusz emerytalny całości emisji 52-tygodniowych bonów skarbowych;żadnej z wymienionych wyżej;C
9;Brain drain to zjawisko polegające na:;emigracji pracowników niewykwalifikowanych;emigracji ludzi młodych;emigracji osób o najwyższych kwalifikacjach;emigracji z powodu prześladowań politycznych;C
10;Który z krajów został przyjęty jako ostatni (w 2011/2012 r.) do WTO:;Chiny;Rosja;Indie;Ukraina;B
11;Stawki celne obliczane są w odniesieniu do ceny towaru w przypadku cła:;detalicznego;ad valorem;specyficznego;żadnego z powyższych;B
12;Zawarte w taryfie celnej UE stawki konwencyjne są stosowane w odniesieniu do:;krajów rozwijających się;krajów członkowskich UE;krajów członkowskich WTO;krajów członkowskich NAFTA;C
13;Który z poniższych instrumentów nie należy do środków pozataryfowych:;ograniczenia ilościowe;opłaty wyrównawcze;subsydia eksportowe;dobrowolne ograniczenia eksportu;B
14;Które z poniższych stwierdzeń jest prawdziwe? Kartel międzynarodowy...;jest porozumieniem producentów w celu uzyskania zysku monopolistycznego;polega na monopolizacji rynku światowego przez jednego producenta;nie występuje w praktyce;występuje w praktyce, ale jego działalność nigdy nie zakończyła się sukcesem;A
15;Zasada, według której produkty importowane nie mogą być wprowadzone na rynek na mniej dogodnych warunkach niż krajowe to:;zasada wzajemności;klauzula narodowa;zasada niedyskryminacji;System Powszechnych Preferencji Celnych;B
16;Wskaż błędną odpowiedź: Jednym z warunków sukcesu kartelu międzynarodowego jest:;względnie stabilny popyt;wysoka elastyczność cenowa popytu;mała elastyczność podaży producentów nie należących do kartelu;niska elastyczność cenowa popytu;B
17;OPEC to organizacja skupiająca:;importerów i eksporterów ropy naftowej;korporacje-eksporterów ropy naftowej;państwa-eksporterów ropy naftowej;żadna z powyższych odpowiedzi nie jest prawidłowa;C
18;W celu uwzględnienia różnic w poziomach cen krajów, w porównaniach międzynarodowych stosuje się:;ceny stałe;dynamikę inflacji;stopę parytetu siły nabywczej;deflator;C
19;Celem uzyskania nadwyżki eksportowej określonego dobra stosowane są:;dobrowolne ograniczenia eksportu;subsydia produkcji krajowej;subsydia eksportowe;opłaty wyrównawcze;C
20;Dumping jest stosowany przez:;eksporterów;rząd kraju eksportującego;rząd kraju importera;importerów;A
21;Zestawienie wpływów i wydatków z tytułu obsługi kapitału i pracy zawiera:;Bilans obrotów kapitałowych;Bilans transferów jednostronnych;Bilans obrotów bieżących;Bilans obrotów wyrównawczych;C
22;Zobowiązanie w polskim bilansie płatniczym powstaje, gdy:;CARITAS przekaże żywność Ukrainie;obywatel Niemiec otrzyma dywidendę z akcji Polska Miedź S.A.;niemiecka firma Bosch zakupi agregaty od firmy Polar;polska firma Reserved zakupi bawełnę w Indiach;D
23;Równowaga bilansu płatniczego występuje w sytuacji, gdy:;równoważą się transakcje autonomiczne oraz wyrównawcze;transakcje autonomiczne równoważą się, a transakcje wyrównawcze nie występują;dzięki transakcjom wyrównawczym równoważą się transakcje autonomiczne;żadne z tych stwierdzeń nie jest prawdziwe;B
24;Walutę, w stosunku do której notowane są ceny innych walut, nazywamy:;walutą podstawową;walutą kluczową;walutą efektywną;walutą bazową;D
25;Przy pozostałych warunkach bez zmian aprecjacja waluty czyni produkty dla zagranicznych odbiorców:;droższymi;tańszymi;nie ma na to wpływu;żadna odpowiedź nie jest poprawna;A
26;Realna stopa procentowa to:;nominalna stopa procentowa skorygowana o poziom deprecjacji;nominalna stopa procentowa skorygowana o poziom inflacji;nominalna stopa procentowa skorygowana o poziom stóp u partnera handlowego;wszystkie powyższe odpowiedzi są prawidłowe;B
27;Wykorzystywanie różnic oprocentowania lokat w kraju i za granicą to:;arbitraż kursowy;arbitraż procentowy;arbitraż walutowy;arbitraż depozytowy;B
28;Jeżeli kurs terminowy waluty jest wyższy od kursu bieżącego, to różnicę tę nazywamy:;marżą;dyskontem;premią;rentą spekulacyjną;C
29;Względne obniżenie stopy procentowej w danym kraju z reguły powoduje:;aprecjację jego waluty narodowej;deprecjację jego waluty narodowej;nie powoduje ani aprecjacji nie deprecjacji;żadne z tych stwierdzeń nie jest prawdziwe;B
30;Istniejący do 1914 roku system waluty złotej był systemem walutowym:;z kursem arbitralnym;z kursem zmiennym;z kursem stałym;z kursem zmiennym kontrolowanym;C
31;Amerykański dolar stał się kluczowym pieniądzem międzynarodowym:;w systemie waluty złotej;w okresie międzywojennym;w systemie z Bretton Woods;w systemie kursów zmiennych;C
32;Stan rezerw walutowych w Polsce wynosił na koniec kwietnia 2023 roku około:;78 mld USD;108 mld USD;178 mld USD;228 mld USD;C
33;Kto nie ponosi ryzyka kursowego, jeżeli walutą płatności jest waluta kraju trzeciego:;importer;eksporter;obaj ponoszą;żaden z nich nie ponosi;C
34;W systemie z Bretton Woods bezpośrednio wymienialne na złoto były:;wszystkie waluty uczestniczące w systemie;tylko USD;tylko GBP;żadna waluta nie była wymienialna;B
35;Źródłem pożyczek udzielanych przez MFW są wkłady państw członkowskich do Funduszu. Są to:;kwoty;SDR-y;transze;żadne z powyższych;A
36;Udzielaniem pożyczek wyłącznie prywatnym przedsiębiorstwom bez gwarancji rządowej zajmuje się:;OECD;IBRD;Międzynarodowa Korporacja Finansowa;IDA;C
37;Koordynację polityki wewnętrznej, obronnej oraz zagranicznej krajów ugrupowania przewiduje:;unia walutowa;unia polityczna;unia ekonomiczna;wspólny rynek;B
38;Przyjęty przez ONZ w 2000 r. program walki z nędzą (kontynuowany jako Agenda 2030) to:;IDA;ODA;AID;MDG;D
39;Który z krajów ma największy stosunek długu publicznego do PKB:;Włochy;Grecja;USA;Japonia;D
40;Im wyższa bariera celna zostanie usunięta przy tworzeniu ugrupowania, tym korzyści są:;większe;mniejsze;ani mniejsze, ani większe;wszystkie odpowiedzi są błędne;A`;
//"Międzynarodowe studia bezpieczeństwa"
//Blok3
const baza3 = `ID;Pytanie;A;B;C;D;Klucz
1;W jakich latach miała miejsca wojna domowa w Tadżykistanie?;1992-1997;1997-2000;1990-1992;2000-2010;A
2;Jak nazywa się ugrupowanie terrorystyczne radykałów muzułmańskich działające w Azji Centralnej (zwłaszcza w Uzbekistanie) od 1998 roku?;Islamski Ruch Afganistanu;Islamski Ruch Uzbekistanu;Islamski Ruch Pamiru;Islamski Ruch Kirgistanu;B
3;W którym roku powstała Regionalna Struktura Antyterrorystyczna w ramach Szanghajskiej Organizacji Współpracy?;w 2004 roku;w 2005 roku;w 2001 roku;w 2006 roku;A
4;Gdzie ma siedzibę Szanghajska Organizacja Współpracy?;W Biszkeku;W Moskwie;W Astanie;W Pekinie;D
5;Co oznacza skrót VPN w kontekście bezpieczeństwa transmisji danych?;Virtual Private Network;Visual Private Network;Video Private Network;Visual Protected Network;A
6;Wykorzystanie technologii informacyjnych do celów wojskowych zostało zapisane w Doktrynie Federacji Rosyjskiej w:;2014 roku;2022 roku;1994 roku;1945 roku;A
7;Plan ciągłości działania:;ma postać uniwersalną;są unikalne dla każdej instytucji;jest wymagany tylko dla dużych korporacji;jest opcjonalny;B
8;Działania cyberprzestępców są:;zregionalizowane;uniwersalne na całym świecie;ograniczone do krajów rozwiniętych;skierowane wyłącznie przeciwko instytucjom rządowym;A
9;Wśród celów ataków atrakcyjnych dla terrorystów w cyberprzestrzeni znajdują się systemy kontrolne sektorów:;transportowego, finansowego, energetycznego;zaopatrzenia w wodę, żywność, łączności;transportu wodnego, lądowego i powietrznego;wszystkie odpowiedzi są poprawne;D
10;W wojnie hybrydowej jednowymiarowy obraz wojny zastąpiony został kompleksem działań militarnych i pozamilitarnych. Oznacza to, że:;działania mogą toczyć się nie tylko na fizycznym polu bitwy;nie tylko regularne jednostki są wykorzystywane;wojna hybrydowa jest z natury polimorficzna;wszystkie odpowiedzi są prawdziwe;D
11;Zmasowany odwet i elastyczne reagowanie to:;Strategia brytyjska w II wojnie światowej;Elementy niemieckiej wojny błyskawicznej;Strategia jądrowej z okresu zimnej wojny;Żaden powyższych;C
12;Europejska ekspansja globalna rozpoczęła się:;W połowie XIII wieku;W końcu XV wieku;W II połowie XVIII wieku;W XIX wieku;B
13;Wielki kryzys rozpoczął się od:;Recesji po traktacie wersalskim;Traktatu w Trianon;Krachu na giełdzie nowojorskiej w 1929 roku;Programu New Deal;C
14;Załamanie tzw. „ładu wiedeńskiego” doprowadziło do:;Hegemoni Rosji w Europie;Procesu dekolonizacji;Wybuchu II wojny światowej;Wybuchu I wojny światowej;D
15;Ustawa zasadnicza – Konstytucja jest:;Aktem prawnym wyższego rzędu w stosunku do ustawy;Aktem prawnym niższego rzędu;Aktem wykonawczym do rozporządzenia;Żadne z powyższych;A
16;Organizacja Narodów Zjednoczonych:;Jest międzynarodową organizacją regionalną;Jest organizacją uniwersalną powstałą w 1920 roku;Jest organizacją uniwersalną powstałą w 1945 roku;Żadne z powyższych;C
17;Rada Bezpieczeństwa ONZ składa się z:;6 członków stałych i 5 niestałych;10 członków stałych i 5 niestałych;6 członków stałych i 9 niestałych;5 członków stałych i 10 niestałych;D
18;Radziecka interwencja w Afganistanie rozpoczęła się:;w grudniu 1979 roku;13 grudnia 1981 roku;15 lutego 1989 roku;4 czerwca 1989 roku;A
19;Przyczyną operacji „Żelazne miecze” Izraela w Strefie Gazy (2023) był:;Ataki Hezbollahu z 24 listopada 2023;Atak Hamasu na południowy Izrael 7 października 2023;Atak rakietowy Teheranu z 10 grudnia 2023;Żadne z powyższych;B
20;Górski Karabach:;Jest terytorium Azerbejdżanu kontrolowanym przez Armenię;Niepodległym państwem uznawanym przez społeczność;Przestał istnieć 1 stycznia 2024 roku;Jest obszarem Armenii pod okupacją;C
21;Trwający od 1947 roku konflikt pomiędzy Indiami i Pakistanem dotyczy:;Hajdarabadu;Dżammu i Kaszmiru;Arunachal Pradesh;Pendżabu;B
22;Hezbollah:;Jest organizacją sunnicką;Jest organizacją szyicką wspieraną przez Iran;Jest sunnicką organizacją w Nigerii;Organizacją bojowników kurdyjskich;B
23;Który etap przewrotu ideologicznego nie pasuje do pozostałych?;demoralizacja;destabilizacja;kryzys;wojna;D
24;Przyjęta wersja dezinformowania przeciwnika to:;scenariusz;plan;legenda;temat;C
25;Subiektywne wyobrażenie, jakie jednostka ma o danym obiekcie to:;wizerunek;wizja;marzenie;obraz;A
26;Wizerunek, do którego sięga jednostka jako punktu odniesienia to:;wizerunek równoległy;wyobrażenie;wizja;marzenie;A
27;Mechanizmy kontrolne w analizie ryzyka dzielą się na:;Mechanizmy wykrywające, nakazujące, prewencyjne, korekcyjne;Mechanizmy wykrywające, nakazujące, prewencyjne, profilaktyczne;Mechanizmy wykrywające, naprawcze, prewencyjne, profilaktyczne;Mechanizmy informacyjne, kontrolujące, nadzorujące, odwoławcze;A
28;Informacje to:;inna nazwa danych;dane przetworzone w kontekście;dane przetworzone w formę;odpowiedzi b i c są poprawne;D
29;Konwencja o cyberprzestępczości z 2001 r. obejmuje:;nielegalny dostęp, oszustwo, nielegalne treści, fałszowanie;kradzieże tożsamości, szpiegostwo, pranie pieniędzy, terroryzm;zniesławienie, nękanie, groźby;przemyt ludzi, handel narkotykami, korupcję;A
30;Czy hacking jest przestępstwem komputerowym skierowanym głównie przeciwko:;ochronie informacji;mieniu;bezpieczeństwu publicznemu;wiarygodności dokumentów;A`;
//"Instytucje i prawo międzynarodowe"
//Blok4
const baza4 = `ID;Pytanie;A;B;C;D;Klucz
1;Norma prawna składa się z:;Hipotezy, dyspozycji i sankcji;Zakazu określonego zachowania;Nakazu określonego zachowania;Sugestii określonego zachowania wobec podmiotu prawa;A
2;Norma prawna jest:;Tworzona i sankcjonowana przez państwo;Tworzona przez społeczeństwo;Sankcjonowana przez negatywne reakcje społeczne wobec naruszyciela normy;Kształtowana wyłącznie przez tradycje danej kultury narodowej;A
3;Państwo jest organizacją:;Składającą się z terytorium, ludności i zdolną do efektywnego sprawowania władzy;Utworzoną przez inne państwa;Utworzoną przez Organizację Narodów Zjednoczonych;Stanowiącą obszar z wyraźnie określonymi granicami wewnętrznymi;A
4;Stosunek prawny to:;Relacja pomiędzy dwoma lub więcej podmiotami prawa;Akt jednostronny podmiotu prawa;Relacja oparta na uznaniu przez społeczeństwo;Przymus państwa wobec obywatela;A
5;Prawo publiczne:;Reguluje ustrój organów władzy państwowej, ich kompetencje, zasady i formy działania;Reguluje stosunki majątkowe pomiędzy obywatelami;Reguluje stosunki niemajątkowe pomiędzy obywatelami;Reguluje stosunki pomiędzy rodzicami a dziećmi;A
6;Źródłami powszechnie obowiązującego prawa Rzeczypospolitej Polskiej są:;Konstytucja, ustawy, ratyfikowane umowy międzynarodowe oraz rozporządzenia;Rezolucje Zgromadzenia Ogólnego Organizacji Narodów Zjednoczonych;Uchwały Parlamentu Europejskiego;Normy prawa stanowione przez ogół społeczeństwa;A
7;Władzę wykonawczą w Rzeczypospolitej Polskiej sprawują:;Prezydent RP i Rada Ministrów;Premier RP;Sejm i Senat;Społeczeństwo podejmujące decyzje w drodze referendum;A
8;Podstawową zasadą prawa cywilnego jest:;Zasada równości podmiotów prawa cywilnego;Zasada przymusu państwa wobec obywatela;Uprzywilejowana pozycja osób prawnych wobec osób fizycznych;Możliwość nakładania kar administracyjnych przez spółki prawa handlowego na inne podmioty prawa cywilnego;A
9;Przestępstwo to:;Czyn zabroniony pod groźbą kary przez ustawę obowiązującą w chwili jego popełnienia, zawiniony i społecznie szkodliwy w stopniu wyższym niż znikomy;Czyn niedozwolony;Każde działanie naruszające dyspozycję normy prawnej;Czyn polegający na sprzeciwianiu się decyzjom władz politycznych państwa;A
10;Prawo administracyjne materialne zostało skodyfikowane:;W Kodeksie administracyjnym;Ustawie o funkcjonowaniu państwa;Nie zostało skodyfikowane i składa się z norm zawartych w wielu ustawach;Kodeksu postępowania administracyjnego;C
11;Norma prawa międzynarodowego publicznego powstaje:;Z woli państw;Na mocy rezolucji Zgromadzenia Ogólnego ONZ;Jednostronnych aktem prawnym państwa;Orzeczeniem Międzynarodowego Trybunału Sprawiedliwości;A
12;Zwyczaj międzynarodowy jako źródło prawa wynika z:;Ogólnej praktyki państw przyjętej za prawo;Judykatury;Poglądów posiadających najwyższe kwalifikacje znawców prawa międzynarodowego (doktryny);Rezolucje Zgromadzenia Ogólnego ONZ;A
13;Główną funkcją prawa międzynarodowego publicznego jest:;Regulowanie stosunków zewnętrznych państw;Określenie ustroju politycznego państw świata;Określenie statusu osób prawnych w państwach świata;Regulowanie stosunków prawnych pomiędzy obywatelami różnych państw;A
14;W myśl Konstytucji RP władze wykonawczą w Polsce:;sprawują Prezydent Rzeczypospolitej Polskiej, Sejm i Senat;sprawuje Prezes Rady Ministrów;sprawuje Prezydent Rzeczypospolitej Polskiej;sprawują Prezydent Rzeczypospolitej Polskiej i Rada Ministrów;D
15;Podmioty prawa międzynarodowego dzielą się na:;Pierwotne (państwa) i wtórne (organizacje międzynarodowe);Państwa, organizacje międzynarodowe i osoby fizyczne;Państwa suwerenne i państwa niesuwerenne;Podmioty samoistne i ustanowione przez Organizację Narodów Zjednoczonych;A
16;Prawo veta wielkich mocarstw oznacza, że:;Decyzje Rady Bezpieczeństwa ONZ w sprawach proceduralnych zapadają większością głosów 9 członków, a we wszystkich innych sprawach większością 9 członków, wliczając w to głosy wszystkich stałych członków RB;Wszystkie decyzje Rady Bezpieczeństwa zapadają większością 9 członków, wliczając w to głosy wszystkich stałych członków RB;Stali członkowie Rady Bezpieczeństwa mają prawo veta wobec rezolucji Zgromadzenia Ogólnego ONZ;Rezolucje Zgromadzenia Ogólnego ONZ w sprawach proceduralnych wymagają jednomyślności wielkich mocarstw;A
17;Podstawową funkcją misji dyplomatycznej jest:;Reprezentowanie państwa wysyłającego w państwie przyjmującym;Pełnienie czynności notariusza i urzędnika stanu cywilnego pod warunkiem zgodności z przepisami miejscowymi;Wykonywanie nadzoru i kontroli nad statkami i samolotami;Wystawianie paszportów i wiz;A
18;Prawo nieszkodliwego przepływu oznacza, że:;Przepływ jest nieszkodliwy, dopóki nie zagraża pokojowi, bezpieczeństwu i porządkowi państwa nadbrzeżnego;Statek dokonujący przepływu ogranicza się wyłącznie do ładowania lub wyładowywania towarów;Statek dokonujący przepływu ogranicza się do uprawiania rybołówstwa;Statek dokonujący przepływu jest holowany przez statek bandery państwa nadbrzeżnego;A
19;Układ o tranzycie międzynarodowych służb powietrznych zawiera:;Prawo przelotu nad terytorium państwa bez lądowania i prawo lądowania w celach niehandlowych;Prawo zabierania pasażerów i ładunków do i z krajów trzecich;Prawo przywożenia pasażerów z kraju rejestracji statku powietrznego;Prawo zabierania pasażerów im ładunków do kraju przynależności statku powietrznego;A
20;Komisja koncyliacyjna po zbadaniu sporu:;Zaleca państwom spór wiodącym konkretne rozstrzygniecie;Wydaje decyzję wiążącą strony spór wiodące;Redaguje dokument zawierający opis stanu faktycznego i na tym kończy swoją działalność;Wydaje wyrok rozstrzygający spór;A
21;Zgodnie z Konwencją Prawo Traktatów umowa międzynarodowa to:;Międzynarodowe porozumienie między państwami regulowane przez prawo międzynarodowe;Jednostronne oświadczenie woli państwa wywołujące skutki prawnomiędzynarodowe;Rezolucja Zgromadzenia Ogólnego ONZ zawierająca tekst umowy międzynarodowej;Uchwała instytucji międzynarodowej;A
22;Umowa międzynarodowa musi nosić nazwę:;Konwencji międzynarodowej;traktatu międzynarodowego;Porozumienia międzynarodowego;Nazwa nie ma znaczenia;D
23;Ratyfikacja oznacza:;Zatwierdzenie podpisanej umowy międzynarodowej przez upoważniony do tego organ państwa;Opublikowanie umowy międzynarodowej w urzędowym zbiorze praw państwa członkowskiego;Zarejestrowanie umowy międzynarodowej w sekretariacie ONZ;Podpisanie umowy międzynarodowej przez negocjatorów;A
24;Umieszczenie w umowie międzynarodowej klauzuli narodowej oznacza:;Strona traktuje obywateli drugiej strony jak obywateli własnych;Strona traktuje obywateli drugiej strony w taki sposób w jaki jej obywatele traktowani są przez drugą stronę umowy;Strona traktuje obywateli własnych w sposób określony w umowie;Umowa zawiera odesłanie do prawa wewnętrznego strony;A
25;W myśl Konstytucji RP Rzeczpospolita Polska jest:;demokratycznym państwem prawa;demokratycznym państwem prawnym, urzeczywistniającym zasady sprawiedliwości społecznej;demokratycznym państwem prawnym, działającym na zasadzie subsydiarności;żadna z powyższych odpowiedzi nie jest prawidłowa;B
26;Zastrzeżenie złożone przez państwo oznacza, że:;Określone postanowienia umowy państwo będzie interpretować na swój sposób lub też, akceptując umowę, nie uznaje się za związane określony postanowieniem umowy;Państwo składające zastrzeżenie nie przystępuje do umowy;Państwo składające zastrzeżenie nie jest związane żadnymi postanowieniami umowy;Państwo składające zastrzeżenie prezentuje stanowisko polityczne bez skutków prawnych;A
27;Nieważność umowy międzynarodowej oznacza, że:;Umowa nie spełnia warunków określonych przez prawo międzynarodowe i jest nieważna ex tunc;Umowa jest nieważna ex nunc;Państwa członkowskie zyskują uprawnienie do wypowiedzenia umowy;Umowa obowiązuje tylko w części;A
28;Przymus wobec przedstawiciela państwa lub przymus wobec państwa skutkuje:;Bezwzględną zasadniczą nieważnością umowy;Względną nieważnością formalną umowy;Koniecznością konwalidacji;Nieograniczoną nieważnością formalną umowy;A
29;Zasada contra preferentem stosowana przy interpretacji umowy międzynarodowej oznacza:;Postanowienia niejasne należy interpretować na niekorzyść strony, która je podczas negocjacji zaproponowała;Tego co jasne nie należy interpretować;Zobowiązania państw należy interpretować w sposób ścieśniający;Wątpliwości interpretacyjne rozstrzyga się zgodnie z postanowieniami preambuły;A
30;Organizacje międzynarodowe:;Są zaliczane do podmiotów wtórnych prawa międzynarodowego;Są zaliczane do podmiotów pierwotnych prawa międzynarodowego;Nigdy nie są podmiotami prawa międzynarodowego;Funkcjonują na podstawie prawa krajowego;A
31;Organizacje międzynarodowe powoływane są do życia na mocy:;Umowy międzynarodowej;Jednostronnego oświadczenia państwa;Rezolucji Zgromadzenia Ogólnego ONZ;Stanowiska Rady Bezpieczeństwa ONZ;A
32;Funkcje organizacji międzynarodowych obejmują:;Funkcje regulacyjne, kontrolne i operacyjne;Funkcję stanowienia powszechnie obowiązujących norm prawa międzynarodowego;Funkcję zorganizowanego aparatu przymusu w stosunkach międzynarodowych;Funkcję określania statusu prawnego obywateli w państwach członkowskich;A
33;Sekretariat (biuro) organizacji międzynarodowej to organ:;Składający się z funkcjonariuszy międzynarodowych, wykonujący czynności techniczno – administracyjno – biurowe;Posiadający kompetencje wykonawcze;Składający się z upełnomocnionych przedstawicieli państw członkowskich;Składający się z pracowników podległych państwom delegującym;A
34;Funkcjonariusze organizacji międzynarodowych:;Reprezentują delegujących ich państwa członkowskie;Podlegają władzy państwa delegującego;Podlegają osobie stającej na czele zespołu funkcjonariuszy organizacji;Nie podlegają nikomu jako wolontariusze;C
35;Organizacja Narodów Zjednoczonych:;Jest uniwersalną organizacja międzynarodową utworzoną na podstawie Karty Narodów Zjednoczonych;Jest organem międzynarodowym tworzącym powszechnie obowiązujące normy prawa międzynarodowego;Pełni funkcje konsultacyjne dla korporacji międzynarodowych;Posiada kompetencje przyznane przez Zgromadzenie Ogólne ONZ;A
36;NATO jest organizacją o charakterze:;Polityczno-wojskowym, składającą się ze struktury cywilnej i militarnej;Uniwersalnym;Polityczno-gospodarczym, propagującą idee wolnego handlu;Humanitarnym, zajmującą się kontrolą przestrzegania praw człowieka przez państwa członkowskie;A
37;Unia Europejska:;Posiada kompetencje określone w traktatach założycielskich przez państwa członkowskie;Posiada kompetencje określone przez Trybunał Sprawiedliwości;Posiada kompetencje określone przez Zgromadzenie Ogólne ONZ;Posiada wyłącznie kompetencje przydzielane ad hoc przez państwa członkowskie;A
38;Rada Europy:;Jest organem Unii Europejskiej;Jest organizacją międzynarodową utworzoną przez Unie Europejską;Składa się z szefów państw i rządów państw członkowskich Unii Europejskiej;Jest organizacją działającą na rzecz przestrzegania praw człowieka;D
39;Podejmowanie uchwał w systemie contracting out oznacza, że:;Państwo członkowskie nie musi wyrażać zgody na związanie się uchwała, natomiast może legalnie nie przyjąć zobowiązania, składając w określonym terminie odpowiednie oświadczenie;Państwo członkowskie odmawia udziału w głosowaniu nad przyjęciem uchwały i nie jest związane jej postanowieniami;państwo członkowskie głosuje przeciwko przyjęciu uchwały, a jeśli – wbrew jego stanowisku – uchwała zostaje przyjęta, nie jest ono związane jej postanowieniami;państwo członkowskie głosuje przeciwko przyjęciu uchwały, a jeśli – wbrew jego stanowisku – uchwała zostaje przyjęta, następuje automatyczne zawieszenie członkostwa państwa w organizacji;A
40;Odpowiedzialności karnej podlega ten tylko, kto popełnia czyn:;zabroniony, przez ustawę, obowiązującą w czasie jego popełnienia;zabroniony, pod groźbą kary, przez ustawę;zabroniony, pod groźbą kary, przez ustawę, obowiązującą w czasie jego popełnienia;zabroniony przez ustawę;C
41;Czyn zabroniony, którego społeczna szkodliwość jest znikoma:;stanowi przestępstwo;nie stanowi przestępstwa;może stanowić przestępstwo, na podstawie wyroku sadu;może stanowić przestępstwo, o ile jest on zabroniony przez ustawę;B
42;Skargę kasacyjną do Naczelnego Sądu Administracyjnego wnosi się w terminie:;30 dni od dnia wydania orzeczenia przez sąd I instancji;60 dni od dnia wydania orzeczenia przez sąd I instancji;30 dni od dnia doręczenia stronie odpisu orzeczenia wraz z uzasadnieniem;30 dni od dnia sporządzenia przez sąd uzasadnienia;C
43;Przestępstwo jest:;występkiem albo wykroczeniem;zbrodnią albo występkiem;zbrodnią albo wykroczeniem;zbrodnią, występkiem lub wykroczeniem;B
44;Zbrodnią jest czyn zabroniony zagrożony kara pozbawienia wolności na czas nie krótszy od lat:;2 albo karą surowszą;3 albo kara surowszą;5 albo kara surowsza;10 albo kara surowsza;B
45;Warunkowego umorzenia postepowania karnego nie stosuje się wobec sprawcy czynu, który:;nie przeprosił pokrzywdzonego;był poprzednio karany za przestępstwo nieumyślne;był poprzednio karany za przestępstwo umyślne;był poprzednio karany za wykroczenie umyślne;C
46;Stan nietrzeźwości zachodzi, gdy zawartość alkoholu we krwi przekracza:;0,2 promila albo prowadzi do stężenia przekraczającego tę wartość;0,1 promila albo prowadzi do stężenia przekraczającego tę wartość;0,4 promila albo prowadzi do stężenia przekraczającego te wartość;0,5 promila albo prowadzi do stężenia przekraczającego te wartość;D
47;Umowa zobowiązująca do przeniesienia własności nieruchomości powinna być zawarta:;w formie pisemnej;w formie pisemnej przewidzianej dla celów dowodowych;w formie aktu notarialnego;w formie pisemnej z podpisami notarialnie poświadczonymi;C
48;W myśl Konstytucji RP na podstawie i w granicach prawa działają:;organy naczelne państwa;Prezydent i Rada Ministrów;organy władzy publicznej;Sejm, Senat, Prezydent i Rada Ministrów;C
49;W myśl Konstytucji RP każdego uważa się za niewinnego, dopóki:;jego wina nie zostanie stwierdzona wyrokiem sądu;jego wina nie zostanie stwierdzona wyrokiem sądu II instancji;jego wina nie zostanie stwierdzona wyrokiem sądu I instancji;jego wina nie zostanie stwierdzona prawomocnym wyrokiem sądu;D
50;W myśl Konstytucji RP akty prawa miejscowego:;są źródłami prawa powszechnie obowiązującego, jedynie na obszarze działania jednostek samorządu terytorialnego;nie są źródłami prawa powszechnie obowiązującego;są źródłami powszechnie obowiązującego prawa Rzeczypospolitej Polskiej na obszarze działania organów, które je ustanowiły;żadna z powyższych odpowiedzi nie jest prawidłowa;C`;
//"Studia regionalne i globalne"
//Blok5
const baza5 = `ID;Pytanie;A;B;C;D;Klucz
1;W geopolitycznej teorii Halforda Mackindera „osią świata” (pivot area), a później „regionem rdzeniowym” (heartland) nazwano:;Afrykę;Rosję i otaczające regiony;Europę Zachodnią;Australię;B
2;ONZ jest organizacją obejmującą z zasady państwa:;demokratyczne;rozwijające się;suwerenne;produkujące ropę;C
3;Zasadę suwerenności i równości państw wprowadził w system międzynarodowy:;Traktat Wersalski;Traktat Westfalski;Traktat Wiedeński;Traktat Lizboński;B
4;Niektóre państwa, które podczas Zimnej Wojny nie należały ani do NATO, ani do Układu Warszawskiego, organizowały się w:;Ruchu Państw Niezaangażowanych;UNESCO;Światowym Związku Krajów Marnych;Międzynarodowym Klubie Dysydentów;A
5;Kraj o znaczącym wpływie na inne państwa oraz w roli lidera nazywa się:;mediatorem;hegemonem;dyktatorem;innowatorem;B
6;Do krajów Zachodu liczy się m.in.:;Tajlandia;Łotwa;Namibia;Paragwaj;B
7;Za najważniejszego twórcę tzw. niemieckiej szkoły geopolityki uchodzi:;Alexander von Humboldt;Karol Marks (Karl Marx);Friedrich Ratzel;Otto von Bismarck;C
8;Zimna Wojna była konfliktem o charakterze:;politycznym;gospodarczym;ideologicznym;wszystkie powyższe odpowiedzi są prawidłowe;D
9;Polska przystąpiła do NATO (razem z Czeską Republiką i Węgrami) w roku:;1999;1975;1949;2004;A
10;Związek Radziecki rozpadł się na koniec roku:;1945;1991;1933;1961;B
11;Aby zostać kandydatem dla członkostwa w Unii Europejskiej, dane państwo musi:;posiadać system demokratyczny;posiadać gospodarkę wolnorynkową;być położone w Europie;wszystkie powyższe odpowiedzi są prawidłowe;D
12;Jeden z kluczowych elementów, którymi według definicji “klasycznej” musi się wykazać “prawdziwe” państwo, to:;własna produkcja broni;dostęp do morza;naród;stała siedziba w Radzie Bezpieczeństwa ONZ;C
13;Różni reprezentanci geografii politycznej i/lub geopolityki uważali za „granice naturalne” np.:;pasma gór;rzeki;wybrzeża;wszystkie powyższe odpowiedzi są prawidłowe;D
14;Związki polityczne łączące w sposób trwały (i dobrowolny) różne suwerenne państwa i posiadające wspólne instytucje nazywają się:;regionalne;ponadnarodowe;neutralne;międzynarodowe;B
15;Pierwszymi europejskimi mocarstwami, które od XV wieku tworzyły imperia zamorskie, były to:;Anglia i Francja;Rosja i Szwecja;Portugalia i Hiszpania;Niemcy i Belgia;C
16;Od którego państwa Stany Zjednoczone odkupiły w 1803 r. bardzo duże terytorium, co pozwoliło im rozpocząć ekspansję ku zachodowi aż do Pacyfiku, tzw. frontier movement?;Rosja;Wielka Brytania;Hiszpania;Francja;D
17;Państwo wykazujące się szeregiem podmiotów terytorialnych pod szczeblem narodowym o znaczących kompetencjach prawnych i/lub administracyjnych nazywa się:;unitarne;federalne;centralistyczne;oligarchiczne;B
18;Pogląd zachodnich myślicieli i polityków od XVIII wieku, że filozoficzne wartości Oświecenia – np. dotyczące wolności, racjonalizmu lub nowoczesnego zarzadzania państwem – mają być wzorowe dla całego świata, został nazywany:;kosmopolityzmem;imperializmem;uniwersalizmem;komunizm;C
19;Po 1991 roku Samuel Huntington i inni autorzy określili Ukrainę jako kraj podzielony według „linii podziału” (fault line) o charakterze:;religijnym;językowym;politycznym (odnośnie do orientacji polityki zagranicznej);wszystkie powyższe odpowiedzi są prawidłowe;D
20;Integracja regionalna w ogóle zaczyna się od stopniowej integracji struktur:;politycznych;handlowych;fiskalnych;walutowych;B`;
//"Cyberbezpieczeństwo"
//blok6(spec)
const bazaSpec = `ID;Pytanie;A;B;C;D;Klucz
1;Co oznacza w bezpieczeństwie systemów teleinformatycznych tzw. trójca CIA:;Central Intelligence Agency (Centralna Agencja Wywiadowcza);Confidentiality, Integrity, Availability (Poufność, Integralność, Dostępność);Comfort, Identity, Authorization (Komfort, Tożsamość, Autoryzacja);Compact Information Agent (Kompaktowy Agent Informacyjny);B
2;Która ze wskazanych grup stanowi główne źródło zagrożeń dla aplikacji w środowisku informatycznym:;Kierownictwo organizacji;Administratorzy systemów;Księgowość;Sprzedawcy oprogramowania;D
3;Jak brzmi rozwinięcie/pełna nazwa ataku typu DoS:;Denial of Service;Disc Operating System;Double Overtaking Sequence;Domino Operational Substitution;A
4;Wskaż czym jest norma ISO 27001:;Norma dotycząca systemów zarządzania ciągłością działania;Standard tworzenia obrazów płyt cd/dvd;Norma dotycząca systemów zarządzania bezpieczeństwem informacji;Norma dotycząca systemów zarządzania jakością;C
5;Co oznacza skrót VPN w kontekście bezpieczeństwa transmisji danych:;Virtual Private Network (Wirtualna Sieć Prywatna);Visual Private Network (Wizualna Sieć Prywatna);Video Private Network (Wideo Sieć Prywatna);Visual Protected Network (Wizualna Sieć Chroniona);A
6;Która z definicji najlepiej opisuje atak typu phishing:;łowienie ryb za pomocą lasek dynamitu;atak oparty na inżynierii społecznej, najczęściej wykorzystujący wiadomości e-mail, SMSy, MMSy, itp.;atak sieciowy, mający na celu uniemożliwienie działania danemu systemowi IT poprzez nadmierne wykorzystanie/wysycenie dostępnych zasobów;atak na aplikację poprzez przesłanie szkodliwego kodu do formularza wejściowego w aplikacji;B
7;Wskaż podstawowe składowe każdego audytu:;Zakres, Czas, Temat;Temat, Cel, Kryterium;Cel, Zakres, Temat;Cel, Zakres, Kryterium;D
8;Wskaż czym jest audyt pierwszej strony:;audytem zewnętrznym;audytem wewnętrznym;audytem finansowym;audytem technicznym;B
9;Jak należy rozwinąć skrót SZBI:;System Zarządzania Biurem Informatyki;System Zarządzania Bezpieczeństwem Informacji;System Zarządzania Bezpieczeństwem IT;System Zatwierdzania Budżetu Interesariuszy;B
10;Wykorzystanie technologii informacyjnych do celów wojskowych zostało zapisane w Doktrynie Federacji Rosyjskiej w Roku:;2014;2022;1994;1945;A
11;Koncepcję „Czterech Faz Ideologicznego Pogromu" opracował:;Józef Stalin;Aleksander Dugin;Jurij Biezmienow;Dmitrij Miedwiediew;C
12;Osoba, która opracowuje scenariusz zdarzeń mających wprowadzić w błąd to:;dowódca;uczestnik;operator;scenarzysta;C
13;Zarządzanie ryzykiem jest to:;proces planowania zasobów oraz działań zespołu;działanie zmierzające do spowodowania funkcjonowania rzeczy, organizacji lub osób podległych, zgodnie z celami zarządzającego;podejmowanie decyzji i realizacja działań prowadzących do osiągnięcia przez podmiot akceptowalnego poziomu ryzyka;sztuka łączenia różnych środków w celu uniknięcia strat;C
14;Każda metoda analizy ryzyka zawiera wspólne elementy. Można do nich zaliczyć:;identyfikację zagrożeń, ocenę prawdopodobieństwa wystąpienia oraz strat;jedynie zebranie informacji do metodologii;metodologię zarzadzania sytuacją kryzysową;pętlę sprzężenia zwrotnego;A
15;Jakie są narzędzia i techniki ilościowej analizy ryzyka?;Listy kontrolne;Analiza wrażliwości;Listy kontrolne, analiza wrażliwości, analiza drzewa decyzyjnego;Metoda burzy mózgów;C
16;W standardzie zarządzania ryzykiem ISO 31000 pojęcie "ryzyko" oznacza:;niezależność od podmiotu zagrożonego;wpływ niepewności na cel;nadzwyczajność;statystyczną prawidłowość;B
17;Redukcja ryzyka jako zagrożenia związana jest w procesie zarządzania ryzykiem z:;samoubezpieczeniem;finansowaniem ryzyka;identyfikacją ryzyka;kontrolowaniem ryzyka;D
18;Według standardu zarządzania ryzykiem FERMA na ocenę ryzyka składają się:;identyfikacja ryzyka oraz określenie prawdopodobieństwa i skutków;identyfikacja ryzyka, opis ryzyka, pomiar ryzyka, ewaluacja ryzyka;identyfikacja ryzyka i ocena skuteczności działań;pomiar ryzyka i ocena skuteczności działań;B
19;W klasyfikacji ryzyka podział przedmiotowy obejmuje:;ryzyko stałe, ryzyko zmienne;ryzyko wewnętrzne, ryzyko kontroli, ryzyko detekcji;ryzyko systematyczne, obiektywne, prawdopodobieństwa, niepewności;ryzyko subiektywne, właściwe, obiektywne;B
20;Wskaż ciąg pojęć uporządkowany wg właściwej kolejności:;wiedza-dane-informacje-mądrość;mądrość-wiedza-informacje-dane;dane-informacje-wiedza-mądrość;nie ma właściwej kolejności;C
21;"Ukryty Internet" to:;"ciemna sieć", w której odbywają się nielegalne transakcje;sektor sieci dla służb wywiadowczych;zamknięte bazy danych, do których dostęp jest płatny;nieindeksowane dane, do których trudno uzyskać dostęp;D
22;Systemy wspomagające ochroną bezpieczeństwa i porządku publicznego, wykorzystujące analizę Big Data:;służą wskazywaniu prawdopodobnych miejsc popełnienia przestępstwa;korzystają ze zanonimizowanych danych;korzystają z gromadzonych przez ludzi baz, więc powielają ich uprzedzenia;wszystkie odpowiedzi są poprawne;D
23;Analiza wielkich zbiorów jako narzędzie automatyzacji działań służy do:;gromadzenia danych z logów i wykrywania anomalii;wykrywania hakerów na podstawie wzorów zachowań i lokalizacji;dostarczania informacji operacyjnych w czasie rzeczywistym;wszystkie odpowiedzi są poprawne;D
24;3V, czyli opis najważniejszych cech danych przetwarzanych w wielkich zbiorach danych oznacza:;validity, variety, velocity (ważność, zróżnicowanie, szybkość);volume, variety, velocity (objętość, zróżnicowanie, szybkość);validity, value, velocity (ważność, wartość, szybkość);volume, veracity, value (objętość, wiarygodność, wartość);B
25;Internet może być traktowany jako repozytorium wiedzy, ponieważ:;umożliwia dzielenie się informacjami;umożliwia indeksowanie informacji;umożliwia przechowywanie informacji;wszystkie odpowiedzi są prawdziwe;D
26;Wśród istotnych zmian zachodzących we współczesnym świecie w związku z analizą wielkich zbiorów danych należy wymienić zwłaszcza:;nowe rozwiązania w ochronie zdrowia;skuteczne zarządzanie procesami przemysłowymi;usprawnianie komunikacji człowiek-komputer;wszystkie odpowiedzi są poprawne;D
27;Do najważniejszych czynników, wpływających na konieczność dbania o bezpieczeństwo państwa w cyberprzestrzeni, zaliczamy:;przenoszenie aktywności i zagrożeń do cyberprzestrzeni;odmiejscowienie zagrożeń i anonimizacja napastnika;wszystkie powyższe;żadne z powyższych;C
28;Ryzyko, które będzie miało wpływ na cele biznesowe organizacji musi mieć następujące cechy:;być niepewne (prawdopodobieństwo);musi mieć wymierny wpływ (pieniężny lub reputacyjny);obie cechy są prawdziwe;żadna cecha nie jest prawdziwa;C
29;Istotą walki informacyjnej jest:;zniszczenie zasobów informacyjnych przeciwnika;zapewnieniu bezpieczeństwa własnych zasobów;obie odpowiedzi są prawdziwe;żadna z odpowiedzi nie jest prawdziwa;C
30;Definicja "cyberprzestrzeni" w polskim prawie stanowi, że:;cyberprzestrzeń to wirtualny obszar przetwarzania danych;cyberprzestrzeń obejmuje wymiar cyfrowy, fizyczny i ludzki;cyberprzestrzeń to sieć komputerów z dostępem do Internetu;cyberprzestrzeń to pole działania instytucji publicznych i prywatnych;B`;